### ISSUE TITLE
programmatic initialization

### ISSUE THREAD

**Issue by moklick** [schn4ck/schnack#24]
Let user initialize schnack programatically. For example like this: 

```javascript
import Schnack from 'schnack';

const schnack = new Schnack('.comments-go-here', { slug: 'post-slug' });
```

**Comment by styfle** [comment]
Might I suggest changing the first parameter to an `HtmlElement` instead of a selector? This could play nicely with an element that doesn't have an ID or a ClassName.

### Example

```js
const div = document.createElement('div');
const schnack = new Schnack(div, { slug: 'post-slug' });
```

**Comment by moklick** [comment]
I will do something like this for the first parameter:

```javascript
const container = typeof containerParam === 'string' ? 
  document.querySelector(containerParam) :
  containerParam
```

so we can pass a selector or a node.

**Comment by g-div** [comment]
WIP @ #61

**Comment by g-div** [comment]
#61 has been merged and programmatic initialization is now [possible](https://github.com/schn4ck/schnack/blob/master/test/index.html#L20-L29)!
