### ISSUE TITLE
Use a standard open source license

### ISSUE THREAD

**Issue by Calinou** [schn4ck/schnack#38]
The [Lil License v1](https://github.com/gka/schnack/blob/master/LICENSE) isn't a [FSF-approved](https://gnu.org/licenses/license-list.en.html) or [OSI-approved](https://opensource.org/licenses) license.

Would you please consider using a license such as the [MIT License](https://choosealicense.com/licenses/mit/) instead?

**Comment by gka** [comment]
the reason the license isn't approved yet is because it has not been submitted for approval yet.

we'll think about changing the license in the meantime, and let you know soon

**Comment by g-div** [comment]
We should update our license to cover the year 2018, maybe the chance to apply some other changes to it ?

**Comment by gka** [comment]
no problem with changing the year, but aside from that I'd like to keep Lil License.

the argument about not using MIT did convince me:

> **_Why publish yet another license? Why not just use MIT?_**
>
> _It's true that license proliferation is a real problem. And the MIT License is lovely: functional, relatively clear in intent to all readers — not just lawyers — and has stood the test of time. Roughly half of all open source projects use it. But it was written in the 1980s, and as open source authors and users we've learned that, in practice, we need just a little bit more: a declaration of the intent not to use software patents against users, and the shared understanding that contributions back to the project will be incorporated under the same terms of the license._

**Comment by Calinou** [comment]
> a declaration of the intent not to use software patents against users

This may unfortunately pose compatibility isuses with other open source licenses out there, especially the GPLv2.

> and the shared understanding that contributions back to the project will be incorporated under the same terms of the license.

This can be explicitly specified via other means, such as a [Developer Certificate of Origin][https://developercertificate.org/).

**Comment by Calinou** [comment]
> I'm curious as to why this is a problem?

Some users (mainly in corporate areas) are wary of custom licenses, even if it looks they comply to the [Open Source Definition](https://opensource.org/osd).

**Comment by g-div** [comment]
I think that if a corporation would like to adopt *schnack*, which is by itself highly unlikely, and have some concrete issues with the Lil license then we should discuss this again. Right now is like talking about fried air!
