### ISSUE TITLE
Require less privileges from twitter when signing in...

### ISSUE THREAD

**Issue by ssylvan** [schn4ck/schnack#39]
This seems extremely excessive for posting comments on a web site (logging in via twitter). 
![image](https://user-images.githubusercontent.com/1365415/34140090-355dcc14-e42d-11e7-9a34-6b560d38f98a.png)

There's no reason it should get any of that.

**Comment by gka** [comment]
uh, very good point. we're using [passportjs](https://github.com/jaredhanson/passport-twitter) to handle oauth. so far all we're doing is this: https://github.com/gka/schnack/blob/master/src/auth.js#L50-L72

we really don't need or want to post tweets etc.

the github oauth plugin does provide a way to specify the [scope of the request](https://github.com/gka/schnack/blob/master/src/auth.js#L86-L88), but so far I haven't seen anything similar in the [twitter plugin](https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js)

**Comment by gka** [comment]
I opened an issue for this on passport-twitter: https://github.com/jaredhanson/passport-twitter/issues/94

**Comment by g-div** [comment]
When you register an app on twitter, there will be a *"Permissions"* section where you can set the permissions to *"Read only"*.
(Note that you need to regenerate you tokens afterwards)

Is the problem maybe related to these OAuth settings ?

**Comment by gka** [comment]
ah, that's it! btw, I double checked my own schnack twitter app and it was already set to read-only, and therefore, the twitter signin page correctly shows the read-only permissions:

![image](https://user-images.githubusercontent.com/617518/34746923-49003598-f596-11e7-9842-568b85a12f98.png)

so I guess this can be closed

**Comment by gka** [comment]
@ssylvan you need to set the Twitter app permissions to "read-only" in your app's configuration on https://apps.twitter.com (under Application Settings > Access level).

Then it will only ask to read public timeline etc.
