### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Nick-Gottschlich** [schn4ck/schnack#48]
Hi y'all

Just want to start by saying awesome project you've got going, I'm excited to get this up and running.

I'm trying to get schnack up and running on my [homepage](https://nickpgott.com) which is a static site using [gatsbyjs](https://github.com/gatsbyjs/gatsby). I've added the script tag (you can see [here](https://github.com/Nick-Gottschlich/ng-homepage-2/blob/master/src/templates/blog-post.js#L59-L63)) to all my blog posts and deployed.

I set up a subdomain at schnack.nickpgott.com (nearlyfreespeech.net is my webhost). I ssh'd in and went to `/home/private` , `git clone`'d this repo, went into the folder and did `npm install` and `npm run server`. I set up my `config.json` file too with the necessary stuff.

Then I went to `/home/public` and copied over the embed.js so it would be accessible at https://schnack.nickpgott.com/embed.js

Now on my site I'm seeing an error

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://schnack.nickpgott.com/comments/The%20Effects%20of%20a%202K%20Liked%20Tweet%20on%20Tril%20DLs. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/10564265/34227788-0bcbfd36-e594-11e7-96db-a878911d5993.png">

You can see this too if you pop open the console on one of my [blog posts](https://nickpgott.com/blog/trilTweet/).

I've been looking into CORS stuff a bit to see if I need to configure something on my subdomain's server, but haven't been able to figure it out. I figure I would ask here to see if y'all have any solutions.

One more question too, is there a recommended way to keep the `npm run server` script running? I'm not sure but I think it will break when the connection between my computer and the subdomain's server is broken.

Thanks in advance, and for all of your hard work on this!

**Comment by janpio** [comment]
I am not getting the CORS error but only an OPTIONS request to for the comments:
![image](https://user-images.githubusercontent.com/183673/34228228-5075ee06-e5d0-11e7-9677-fe0c2ce37daf.png)

Opening the URL manually with GET returns a 404:
https://schnack.nickpgott.com/comments/The%20Effects%20of%20a%202K%20Liked%20Tweet%20on%20Tril%20DLs
https://schnack.nickpgott.com/comments/foo

**Comment by Nick-Gottschlich** [comment]
I think I set up the "page_url" in the config wrong, let me try modifying that.

**Comment by Nick-Gottschlich** [comment]
Updated the `config.json` to have `page_url` actually link to my blog posts (and am passing in the right slug from the script). I'm still seeing the fetch to the `/comments` url from the old config file. Is there something I need to do to reset the server?

**Comment by moklick** [comment]
Hey Nick. When schnack is up and running you should see an empty page here: https://schnack.nickpgott.com It seems that port 80 doesn't point to 3000 (schnack standard port). You might need to setup a port forwarding for that subdomain to port 3000. You don't need to create a folder "comments". That content gets served by the schnack server.

**Comment by janpio** [comment]
> Is there something I need to do to reset the server?

Kill and restart it, depending on how exactly you started it.

**Comment by gka** [comment]
yep, if schnack is up and running you should get a reply saying `{"test":"ok"}`, like here:
https://schnack.vis4.net/

**Comment by janpio** [comment]
OT: @Nick-Gottschlich NFSN looks interesting, are you using a tutorial for hosting node there?

**Comment by Nick-Gottschlich** [comment]
@janpio Nope, just winging it. No real idea what I'm doing here ha. If you have any suggestions please let me know I'm eager to learn, I know very little about the back end side of website/server hosting.

**Comment by Nick-Gottschlich** [comment]
OK, I followed this tutorial to get node-js set up: http://www.mopsled.com/2015/run-nodejs-on-nearlyfreespeechnet/

The hello world worked, but I get a _(61) Connection refused_ error when trying schnack. I think it could be an issue with the way I'm proxying:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34345428-ff6e97d8-e9bc-11e7-92f2-df467a8ce27d.png">

or my `config.json` file (the ones with `xxxxx` are how they actually are in the config file, the `RETRACTED` ones are an actual secret or id):

```
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ {
    "schnack_host": "https://schnack.nickpgott.com",
    "page_url": "https://nickpgott.com/blog/%SLUG%",
    "port": 8000,
    "admins": [1],
    "oauth": {
        "secret": "xxxxx",
        "twitter": {
            "consumer_key": "RETRACTED",
            "consumer_secret": "RETRACTED"
        },
        "github": {
            "client_id": "RETRACTED",
            "client_secret": "RETRACTED"
        }
    },
    "notify": {
        "pushover": {
            "app_token": "xxxxx",
            "user_key": "xxxxx"
        },
        "webpush": {
            "vapid_public_key": "RETRACTED",
            "vapid_private_key": "RETRACTED"
        },
        "slack": {
            "webhook_url": "xxxxx"
        }
    },
    "date_format": "MMMM DD, YYYY - h:mm a"
}
```

So a couple questions:

* Should I be proxying to the port in the config file? And should that entry be a different port?
* What is the `secret` at the beginning of `oauth`

Oh, and, Merry Christmas 🎄

**Comment by g-div** [comment]
> Should I be proxying to the port in the config file?

Yes.

> And should that entry be a different port?

Different from... ?

> What is the secret at the beginning of oauth?

It's passed to [express-session](https://github.com/expressjs/session#secret).

I've updated the README, hope [this](https://github.com/gka/schnack#configuration) helps.

**Comment by Nick-Gottschlich** [comment]
@g-div What I mean is what port should I be using? Can I just pick any port (like `8000`) or does schnack require a specific port to be used?

**Comment by janpio** [comment]
schnack "locally" can run on any port, most system allow x000+ for this. Then you normally bind public port 80 to it so that it is available directly via its domain.

**Comment by Nick-Gottschlich** [comment]
@janpio sorry, I'm a little confused by what you mean. I have figured out that if I run my `run.sh` script and then do a `curl localhost:3000` I get the correct `{"test":"ok"}` response (I changed the port to `3000` in the config)

![image](https://user-images.githubusercontent.com/10564265/34629039-447c4812-f22c-11e7-987f-28727813e21d.png)

So I have to someone how bind the public facing port 80, to the internally facing port 3000? Which I can set up on the actual server somehow or possibly in the config settings in the nearlyfreespeech.net panel for my site?

**Comment by janpio** [comment]
Config setting on NFS. Probably: Login -> Sites -> Click the site -> Scroll down -> Add a proxy -> "Target Port" = 3000 -> "Add Proxy". But untested for now ;)

**Comment by Nick-Gottschlich** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34635492-f603cf28-f255-11e7-80f3-bcc807868ef0.png">

I have this proxy running but I still get this error:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34635495-0f7ccc34-f256-11e7-9097-c3d6bcb8ef23.png">

Gonna play around with the proxy settings for a while and see what happens.

**Comment by Nick-Gottschlich** [comment]
```
> schnack@0.1.3 server /home/protected/schnack
> NODE_ENV=development nodemon index.js

^[[33m[nodemon] 1.12.1^[[39m
^[[33m[nodemon] to restart at any time, enter `rs`^[[39m
^[[33m[nodemon] watching: *.*^[[39m
^[[32m[nodemon] starting `node index.js`^[[39m
server listening on 3000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_READONLY: attempt to write a readonly database
    at Error (native)
^[[31m[nodemon] app crashed - waiting for file changes before starting...^[[39m
```

Okay, found my way into the logs, looks like I might have to somehow set up permissions so that schnack can write to the SQLITE database

**Comment by Nick-Gottschlich** [comment]
Okay, I did `chmod 777 comments.db` and `chmod 777 sessions.db` and now it's up and running! https://schnack.nickpgott.com/

I kind of feel like that's way to many permissions to be giving out, I don't really get how linux permissions work, so if anyone has any advice that would be much appreciated.

Now I see this on my blog posts:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/10564265/34657486-13bfdeac-f3ec-11e7-9303-babe042233b2.png">

Authentication seems to be having some errors:

Twitter gets this:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/10564265/34657491-2ac15946-f3ec-11e7-8dbd-f4a56fa42de7.png">

```
Error: Could not authenticate you.
    at Strategy.parseErrorResponse (/home/protected/schnack/node_modules/passport-twitter/lib/strategy.js:202:14)
    at Strategy.OAuthStrategy._createOAuthError (/home/protected/schnack/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /home/protected/schnack/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /home/protected/schnack/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/protected/schnack/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/protected/schnack/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

and GitHub gets this:

```
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/10564265/34657496-3f162d72-f3ec-11e7-9593-21c06abd5eec.png">
```

but hey, progress!

**Comment by g-div** [comment]
Did you correctly configured the callback URLs on Github and Twitter ? Do you use the right `client_id` and `client_secret` ? Check you configuration and if you still thinking this is a schnack's bug, feel free to open another specific issue about your authentication problems. I will close this one to avoid to go off-topic.

**Comment by poVoq** [comment]
I am trying to embedd Schnack on a Blogger page and have also run into what appears to be a CORS issue. Schnack returns test:ok fine (running on Phusion Passenger via Plesk) and embedding it on a page with the same main domain seems to work.

But on my blogspot.com Blog (or any other different domain) I get an browser error:
`SecurityError: The operation is insecure.`(Firefox).

Anyone had luck with a similar setting? I am still new to this kind of CORS stuff, so maybe I am overlooking something obvious. Thanks!
