### ISSUE TITLE
Callback URL mismatch - breaking schnack implementation

### ISSUE THREAD

**Issue by Nick-Gottschlich** [schn4ck/schnack#51]
Hello,

I've got schnack implemented on my site (you can see it at: https://nickpgott.com/blog/website2/ if you scroll all the way down, hopefully it loads for you).

When I try to click on the `github` OAuth login I see this pop up window and error:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34921988-41fecea0-f94f-11e7-8058-a399fa4c93b4.png">

When I try `twitter` I see this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34922043-0035d5c6-f950-11e7-8933-b326b40c9507.png">

I set the callback URL according to the code I found [here](https://github.com/schn4ck/schnack/blob/313f249298babfcb9d990957a80689daa54dcb99/src/auth.js#L58) for both the github and twitter oauth page:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10564265/34922008-93ab212c-f94f-11e7-81a4-b0604ce10785.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10564265/34922063-59f51090-f950-11e7-9145-1b05ac502212.png">

I've also copied over the appropriate keys to the config.json file on my server. I can provide my config.json file with secrets stripped if that helps.

I'm trying to figure out what's going wrong at this point that is blocking authentication.

**Comment by janpio** [comment]
What `redirect_uri` is being set on the Github one?

**Comment by g-div** [comment]
You should check that `schnack_host` is set to `https://schnack.nickpgott.com`. Otherwise everything looks fine.

**Comment by Nick-Gottschlich** [comment]
@g-div Looks like I had `"schnack_host"` set to `http` instead of `https`. I changed that and go through to the OAuth for Github, entered my account details but now I see:

![image](https://user-images.githubusercontent.com/10564265/34960137-354a085e-f9ff-11e7-991a-b125f068458b.png)

Twitter is still having the same issue as in the screenshot above. I'll try out google and facebook too since I just saw you added those as oauth possibilities.

@janpio I'm not sure what you mean. The `Authorization callback URL` on the OAuth page I set to: `https://schnack.nickpgott.com/auth/github/callback`.

**Comment by g-div** [comment]
I'm not sure where the problem is, but this isn't looking as a "callback URL mismatch" error anymore. `Waiting for schnack.nickpgott.com` looks like a DNS problem or a request hanging. Hard to debug this through. You can eventually try to keep a look at the "Network" tab of Developer Tools in order to find out which request is actually taking so long.

Feel free to open a new issue when you find this out ;)
