### ISSUE TITLE
There have a cross-origin frame error,  when I test schnack at local environment.

### ISSUE THREAD

**Issue by CareyToboo** [schn4ck/schnack#53]
I test  schnack whit my hexo blog at local environment.

my config.json file 
``` 
    "schnack_host": "http://localhost:3000",
    "page_url": "http://localhost:4000/doc.conport/%SLUG%",
    "database": "comments.db",
    "port": 3000,
    "admins": [1],
```

It's occured when I login with github successed.
```
app.get('/auth/github/callback',
    passport.authenticate('github', {
         failureRedirect: '/login'
     }), (request, reply) => {
          reply.redirect('/success'); // go here
     }
);

app.get('/success', (request, reply) => {
     // It's wrong    
     reply.send(`<script>
            document.domain = document.domain.split('.').slice(1).join('.') || 'localhost';
            window.opener.__schnack_wait_for_oauth();
      </script>`);
});
```

the error log in chorme console  
```
success:3 Uncaught DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
```

and I don't how to slove it.

**Comment by gka** [comment]
I think `schnack_host` needs to be a subdomain of localhost. try `http://schnack.localhost`.

**Comment by g-div** [comment]
As described in the docs this is not possible right now:
> The fields schnack_host and page_url should be hosted on the same domain. If your blog is running at https://blog.example.com, then your schnack instance should be reachable at any subdomain of example.com.

The only workaround is to use a subdomain of `localhost`, as already mentioned here. I hope we will fix this problem soon, but it's a little bit tricky.
