### ISSUE TITLE
Load comments box on SPA

### ISSUE THREAD

**Issue by joeshub** [schn4ck/schnack#54]
Hi

First of all awesome project!

I'm integrating this into my blog which I'm building using GatsbyJS. Gatsby is sort of a single page app and ideally it only loads `embed.js` once, on first load, and when you start navigating the site, ideally you don't want to re-load the entire file on each page click.

Is there an internal API to Schnack that I can use to initialize the schnack comment box programmatically?

Thank you

**Comment by moklick** [comment]
Hey, thanks! Not yet but it's on our list: #24

**Comment by subutuo** [comment]
a
