### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by joeshub** [schn4ck/schnack#55]
Hi 

I've read the docs and looked at the source and can't seem to find where the admin / moderation interface is accessible from.

https://schnack.cool/#administration

Is there a specific path that loads the admin / moderation interface?

I'm also not clear how the `admins` and `secret` entry in the config relates to this.

Again sorry if this too obvious. thank you

**Comment by janpio** [comment]
The admin UI is integrated into the normal comments list I think.

**Comment by moklick** [comment]
The `admins` entry is for specifying the users which are admins. Be default it's `[1]`. So the first user will be an admin. When an admin logs in with one of the providers she can approve or reject a comment directly in the comments section. I just added this information to the docs to make it more clear.

**Comment by gka** [comment]
you’ll see the admin right along with the comments as soon as you’re logged in as admin. 

to make yourself an admin you need to do two things: first you log in once and then check your user id in the sqlite db. if noone else has logged im before you it should be the id 1. second you put this id into the admins setting in the config file. now schnack knows that you’re the admin and will show the moderation buttons along each comment.
