### ISSUE TITLE
Comments on every page

### ISSUE THREAD

**Issue by joeshub** [schn4ck/schnack#56]
For some reason a single comment left on a post is showing on on every post across the site.

Do you have any ideas on how to debug this? 

Here's my config
```
{
    "schnack_host": "http://comments.seifi.org",
    "page_url": "http://seifi.org/%SLUG%",
    ...
}
```

**Comment by janpio** [comment]
The slug is used to differentiate the pages. Is the JS requesting the same data URL for all pages?

**Comment by gka** [comment]
just guessing but could it be that you’re not replacing the slug? the idea is that the slug is unique to each page, but if they all use the same slug they all get the same comments

**Comment by moklick** [comment]
yep, you are requesting the same one on each site. So it shouldn't be http://comments.seifi.org:65515/comments/post-slug but http://comments.seifi.org:65515/comments/apple-ipad-safari-useragent-string-values-ipad-1-ipad-2-ipad-3.html for example

**Comment by joeshub** [comment]
Ah that makes sense now. I'm not sure how I didn't realize the hardcoded string wouldn't magically work. Maybe in the docs it could read something like this to clarify this needs to be dynamic.

thank you for taking a look!

```js
<div class="comments-go-here"></div>
<script src="https://comments.yoursite.com/embed.js"
    data-schnack-slug="YOUR-POST-SLUG-GOES-HERE"
    data-schnack-target=".comments-go-here">
</script>
```

**Comment by rabas007** [comment]
@joeshub - Hi Joe... how did you solve it exactly? I have the same problem. I have to define a `dynamic slug` well as I want to have comments on all my blogposts, unique comments ofcourse pertaining each post.

**Comment by joeshub** [comment]
I just made the value of data-schnack-slug a variable pointing to the page’s slug

**Comment by rabas007** [comment]
@joeshub - Can you please post how you did it exactly? I cannot get it right... even posted my full question here... [https://github.com/hexojs/hexo/issues/3081](url)
