### ISSUE TITLE
session.db is hard-coded, while comments.db can be configured

### ISSUE THREAD

**Issue by rse** [schn4ck/schnack#59]
The `comments.db` has a config option, but in src/auth.js the `sessions.db` is hard-coded and hence cannot be overwritten with a config option. Please add a config option to allow people to set the path to the `sessions.db` file without having to patch the source code of Schnack.

**Comment by gka** [comment]
you can set the `sessions.db` filename in config.json now:
https://github.com/schn4ck/schnack/commit/4c8d8f799ca3951b52ddb2817b6760122dda9618#diff-1bf83e91ce7c86ff1647f9bbc5830578
