### ISSUE TITLE
Hexo + Schnack Tutorial

### ISSUE THREAD

**Issue by dmcmaste** [schn4ck/schnack#63]
Can someone integrate Schnack into a Hexo blog example?

https://schnack.cool/

Thanks!

**Comment by valkalon** [comment]
I'm doing it at the moment Would you like me to post a tutorial once it's done?

**Comment by dmcmaste** [comment]
I would love to see a tutorial! Thanks Valkalon.

**Comment by g-div** [comment]
I think your Hexo theme should just use the Hexo variable [`page.path`](https://hexo.io/docs/variables.html#Page-Variables) to initialize *schnack* like this:

```html
<div class="comments"></div>
<script src="https://comments.example.com/embed.js"
    data-schnack-slug="<% url_for(page.path) %>"
    data-schnack-target=".comments-go-here">
</script>
```

Detailed tutorials are always welcome! You can eventually try to open a PR in the *schnack* [docs](https://github.com/schn4ck/schnack-docs).
