### ISSUE TITLE
Providing TLS Certificate and Key

### ISSUE THREAD

**Issue by simplygreatwork** [schn4ck/schnack#65]
I am so very close to having Schnack setup. But I cannot figure out at all where or how I ought to specify my TLS pem files for the Schnack server. Ideas anyone?

**Comment by g-div** [comment]
schnack's application server is not designed to be responsible of TLS termination and should be served through a [web-server](https://www.nginx.com/resources/glossary/application-server-vs-web-server/) like nginx, apache, caddy...
