### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by rabas007** [schn4ck/schnack#66]
I managed to get Facebook, Github and Google working, but NOT Twitter.

The instructions are straight forward, so not sure where I went wrong...

I also tried... `client_id` and `client_secret` but no luck. Basically, with my Twitter config the whole Schnack breaks down and disappears.

`"twitter": {
            "oauth.twitter.consumer_key": "0TLJKsFQfwefwefwfg4mf3TTcx",
            "oauth.twitter.consumer_secret": "yKco3xftoLssFfwf33rfwgklöSHXi3XeDlgbZSBYiU9vcx2bqepyWvtz"
        },`

**Comment by gka** [comment]
hm, I have it set up on multiple instances with Twitter oauth.

the config is supposed to look like this (note that there are no "oauth.twitter." prefixes)
```json
"twitter": {
            "consumer_key": "xxxxx",
            "consumer_secret": "xxxxx"
},
```

**Comment by rabas007** [comment]
@gka - Hi... that worked, thanks (I had the wrong config for twitter).
