### ISSUE TITLE
Slug?

### ISSUE THREAD

**Issue by rabas007** [schn4ck/schnack#67]
I have a `hexo blog` (hexo.io) with schnack and it works fantastic, apart from the `slug`.

Somehow every comment shows in every blogpost.

I know the issue relates to the `slug` but what to fill in there??? I have this setup for my blog posts...
/source/_posts/hello/post-hello-1
/source/_posts/hello/post-hello-2
/source/_posts/ciao/post-ciao-1
/source/_posts/ciao/post-ciao-2
/source/_posts/ciao/post-ciao-3

etc.

`     <script src="https://schnack.cobracat.win/embed.js" 
      data-schnack-slug="post-slug"
      data-schnack-target=".comments-go-here">
     </script>`

Using `post-slug` does not work. My template language is `EJS`. 

Thanks on forehand for your help.

**Comment by moklick** [comment]
Hey! 

"post-slug" is just a placeholder from our docs. There you need to input the actual slug from a post. In your case "post-ciao-3" for example.
