### ISSUE TITLE
disqus import doesn't work for users with multiple comments

### ISSUE THREAD

**Issue by peppy** [schn4ck/schnack#68]
When an import is run where a user has more than one comments, all posts subsequent to the first will fail on a database error (unique constraint on user provider/provider_id).

Adjusting `saveComment` to

```
    try {
        try {
            await db.run(queries.create_user, author);
        }
        catch (ezz) {}

        const newUser = await db.get(queries.find_user, [author[0], author[1]]);
        if (newUser.id) comment.unshift(newUser.id); // push user_id to the front
        const res = await db.run(`INSERT INTO comment
        (user_id, slug, comment, reply_to, created_at, approved, rejected)
        VALUES (?,?,?,?,?,?,0)`, comment);
        return res.lastID;
    } catch (err) {
        console.error(`Error saving the comment for the slug ${comment[0]}:`, err);
    }
```

resolves this, but obviously isn't the most elegant solution.

Apologies for not PRing a fix myself, in a hurry. Just thought I'd leave this here as I'd like to see as many people moving away from disqus as possible.

Also a note that my disqus export had empty `id`s for all of my posts (I had to pull the slugs out of the `title` fields in the export).

**Comment by g-div** [comment]
We are moving the importer to a [new repository](https://github.com/schn4ck/schnack-importer). This isn't yet on npm, but the problem you are describing is already fixed there. I will push this to npm soon!

**Comment by peppy** [comment]
Thanks, good to know! Will close this as I have already manually solved this issue.

Keep up the great work on the project. Have it up and running on my [blog](https://blog.ppy.sh/dev-changelog-20180324/#comments) now (don't mind the very default styling, will be improved soon)!
