### ISSUE TITLE
suggestion: class rename for "Send Comment" button

### ISSUE THREAD

**Issue by valkalon** [schn4ck/schnack#70]
While styling schnack, I noticed that the "Send comment" button uses the class name "schnack-button".
To me it's confusing as there are several different buttons to style. 
I would suggest to use "schnack-send-comment" as an alternative to be more specific.

**Comment by g-div** [comment]
Yes, we should definitively prepare *schnack* to be styled effectively. Ideally I would like to have a lightweight layer to create and switch themes.
Will look into this ASAP!

**Comment by gka** [comment]
Added `schnack-send-comment` to the class name
