### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by GainfulShrimp** [schn4ck/schnack#74]
I tried to set up an IFTTT recipe to send me a Pushbullet push every time I have new comments, but IFTTT complains "Feed is not reachable at this time.".

If I try to visit https://[myschnackserver]/feed in my browser, I just get "Internal server error." with HTTP status 500.

**Comment by g-div** [comment]
I'm aware that the RSS feed is broken at the moment. This is because we are not using IFTT or PushOver anymore, instead we relies on webpush. Try it !
I will take a look at the RSS feed as well.
