### ISSUE TITLE
Node.js precludes most shared hosting environments

### ISSUE THREAD

**Issue by badbadmonkey** [schn4ck/schnack#89]
Can you not integrate the functionality required. Designing a small comments script such that it can't likely be run on any shared host environment (read: most websites) seems silly.

**Comment by gka** [comment]
you are welcome to design your own comment script in whatever language you prefer. it's a free world 👋

**Comment by styfle** [comment]
On the contrary, Node.js can be deployed to shared hosting environments such as serverless.
