### ISSUE TITLE
Documentation for Google & Facebook OAuth

### ISSUE THREAD

**Issue by badbadmonkey** [schn4ck/schnack#90]
Your instructions for setting up OAuth for the two most common services, Google & Facebook, are blank.

**Comment by leviwheatcroft** [comment]
I can't actually figure out how to get the credentials from google. I think I need to create a project at https://console.developers.google.com, then enable an api, but I'm a bit confused as to what API I need to enable if all I want to do is to authenticate users.
Happy to update the docs once I have this figured out...

**Comment by leviwheatcroft** [comment]
figured out google auth. PR for the docs [here](https://github.com/schn4ck/schnack-docs/pull/1)

**Comment by gka** [comment]
thanks! we're currently adding a simple plugin system to schnack. I will add your docs to https://github.com/schn4ck/schnack-plugins/blob/master/packages/schnack-plugin-auth-google/README.md
